version: '3.7'
services:
  app:
    ports:
      - "${APP_PORT}:8100"
    volumes:
      - app-sync:/app/:nocopy

# that the important thing
volumes:
  app-sync:
    external:
      name: "${DOCKER_BASENAME}_app-sync"